comment  utils folder
LOG8970-Team14/figure_skating_jumps pull request #133
Opened 2023-04-17 15:42 UTC by MrPuffs

2023-04-17 19:20 UTC, chrichriGeorgie reviewed
Juste changer les blocs de paramètres au nouveau format et ça me semblait beau (also mettre les description de throws deuxième dans la liste, mais ça aussi c'est le nouveau format)

2023-04-17 20:12 UTC, cravethedave requested changes

2023-04-17 20:12 UTC, cravethedave commented on lib/utils/exception_utils.dart
> +  /// Throws a specific exception according to the Firebase authentication error code received.
Throws an AbstractIceException according...

2023-04-18 00:45 UTC, cravethedave commented on lib/utils/exception_utils.dart
> +  /// - Throws a [TooManyAttemptsException] if the Firebase auth error code is "too-many-requests".
Je recommande fortement de mettre le type abstrait pour pas avoir un gros comment de meme et que ce soit clair qu'on peut catch AbstractIceException a la place

2023-04-18 01:19 UTC, MrPuffs commented on lib/utils/exception_utils.dart
> +  /// - Throws a [TooManyAttemptsException] if the Firebase auth error code is "too-many-requests".
changed

2023-04-18 01:20 UTC, cravethedave commented on lib/utils/exception_utils.dart
> +  /// - Throws a [FirebaseAuthException] if the Firebase auth error.
It throws an AbstractIceException not a FirebaseAuthException

2023-04-18 02:29 UTC, MrPuffs commented on lib/utils/exception_utils.dart
> +  /// - Throws a [FirebaseAuthException] if the Firebase auth error.
oups sorry

2023-04-18 02:41 UTC, chrichriGeorgie approved these changes

2023-04-18 02:59 UTC, merged