enum folder
LOG8970-Team14/figure_skating_jumps pull request #135
Opened 2023-04-17 18:24 UTC by MrPuffs

2023-04-17 19:28 UTC, chrichriGeorgie requested changes

2023-04-17 19:28 UTC, chrichriGeorgie commented on lib/enums/method_channel_names.dart
> +/// This enum represents the different channels used to exchange data with
This enum contains the differents method channel names used to invoke function declared in the Kotlin project

Je pense que ça décrirait mieux (sinon juste faire la différence method channel et event channel)

2023-04-17 19:28 UTC, chrichriGeorgie commented on lib/enums/x_sens/measuring/measurer_state.dart
> +enum MesurerState { idle, preparing, measuring }
Measurer comme c'était avant

2023-04-17 19:28 UTC, chrichriGeorgie commented on lib/enums/event_channel_names.dart
> +/// the Kotlin side.
This enum contains the differents event channel names used to receive events from the Kotlin project

(Sinon faire la distinction entre method et event channel)

2023-04-17 19:38 UTC, MrPuffs commented on lib/enums/x_sens/measuring/measurer_state.dart
> +enum MesurerState { idle, preparing, measuring }
c'est pas un mot measurer

2023-04-17 19:40 UTC, MrPuffs commented on lib/enums/event_channel_names.dart
> +/// the Kotlin side.
changed

2023-04-17 19:40 UTC, MrPuffs commented on lib/enums/method_channel_names.dart
> +/// This enum represents the different channels used to exchange data with
changed

2023-04-17 19:45 UTC, chrichriGeorgie commented on lib/enums/x_sens/measuring/measurer_state.dart
> +enum MesurerState { idle, preparing, measuring }
Je pense que le bon mot c'est Measurer. Genre de ce que je vois quand je chercher Mesurer (comme tu l'as écrit), n'existe pas.  Je pense que @cravethedave pourrait plus confirmer.

2023-04-17 19:46 UTC, cravethedave commented on lib/enums/x_sens/measuring/measurer_state.dart
> +enum MesurerState { idle, preparing, measuring }
En effet, Measurer est le mot en anglais, et notre langue de prog est l'anglais.
Mesurer est en francais.

2023-04-17 19:53 UTC, cravethedave requested changes
Rename Mesurer to Measurer

2023-04-17 20:07 UTC, cravethedave requested changes

2023-04-17 20:07 UTC, cravethedave commented on lib/enums/models/jump_type.dart
> +/// This enum represents every jump types in figure skating and their associated color.
This enum represents the different jump types done in figure skating as well as the associated color.

2023-04-17 20:07 UTC, cravethedave commented on lib/enums/models/season.dart
> +/// This enum represents all season type in figure skating.
This enum represents the different season types in figure skating.

2023-04-17 20:07 UTC, cravethedave commented on lib/enums/models/user_role.dart
> +/// This enum represents every role of a user.
This enum represents the possible roles of a user.

2023-04-17 20:07 UTC, cravethedave commented on lib/enums/x_sens/measuring/measurer_state.dart
> +/// This enum represents state of the measuring process.
represents the state

2023-04-17 20:07 UTC, cravethedave commented on lib/enums/x_sens/measuring/measuring_status.dart
> +/// This enum represents state of the measuring process.
represents the status
pas state

2023-04-17 20:07 UTC, cravethedave commented on lib/enums/x_sens/recording/recorder_state.dart
> +/// This enum represents state of the recording process.
represents the state

2023-04-17 20:07 UTC, cravethedave commented on lib/enums/x_sens/recording/recording_status.dart
> +/// This enum represents state of the recording process.
represents the status
pas state

2023-04-18 00:43 UTC, cravethedave approved these changes

2023-04-18 00:44 UTC, chrichriGeorgie approved these changes

2023-04-18 00:45 UTC, merged