Update x_sens_dot_connection_button.dart
LOG8970-Team14/figure_skating_jumps pull request #136
Opened 2023-04-17 19:43 UTC by MrPuffs

2023-04-17 20:13 UTC, cravethedave requested changes

2023-04-17 20:13 UTC, cravethedave commented on lib/widgets/buttons/x_sens_dot_connection_button.dart
> +  /// returns a [Route] for the [DeviceManagementView].
removes pas remove
prevent the user
spamming the button
Returns avec majuscule

2023-04-17 22:44 UTC, MrPuffs commented on lib/widgets/buttons/x_sens_dot_connection_button.dart
> +  /// returns a [Route] for the [DeviceManagementView].
changed

2023-04-18 00:45 UTC, chrichriGeorgie approved these changes

2023-04-18 00:47 UTC, cravethedave approved these changes

2023-04-18 00:48 UTC, merged