account creation page + signup rewrite
LOG8970-Team14/figure_skating_jumps pull request #16
Opened 2023-02-26 05:55 UTC by Ch0ufleur

2023-02-26 15:59 UTC, chrichriGeorgie requested changes

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +                                0, 4), // changes position of shadow
Est-ce que le TODO va être fait dans une prochaine branche?
Genre on est sur que ce pourrait pas être utile pour la page de login?

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +                return null;
Ça serait pas pertinent/possible de mettre ça dans une methode pour augmenter la lisibilité du widget en réduisant son nombre de lignes?

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +                return null;
idem pour ici (surtout que y'a des cas qui se répéte genre le no empty.

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +                if (value.length > 255) {
Why la limite maximale de charactère pour le mot de passe? C'est imposé par firebase?

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +                return null;
idem ici pour la méthode

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +                            });
Je vais prendre une méthode ici aussi

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +    }
So finalement on fait rien avec les exception que firebase nous retourne et on duplique la vérification qui est déjà fait pour nous? Vu qu'on ne semble pas setter le accountcreationerror ici. Genre de ce que j'ai vu des vérifications qu'on fait jusqu'à présent, l'utilisateur ne saura jamais ce qui arrive si le mail qu'il a entré est déjà existant (donc qu'il a déjà un account/que son mail s'est fait piraté). Je sais que c'est pas le top niveau sécu (vu que ça révèle qu'un compte existe à ce nom, mais still j'ai l'impression que ça peut être frustrant à la longue)

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +                return null;
Methode ici aussi svp

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/widgets/screens/coach_account_creation_view.dart
> +                return null;
Methode aussi ici, surtout que c'est dupliqué (sorry c'est au début, mais je viens de le voir, mon premier comment la dessus doit être 2-3 comments plus bas)

2023-02-26 15:59 UTC, chrichriGeorgie commented on lib/services/user_client.dart
> +  Future<bool> signUp(
Juste pour être sur de comprendre le retour de bool, comment tu fais dans le UI pour afficher des infos pertinentes pour l'utilisateur dans le cas ou ça retourne false mais que y'a pas une exception qui est throw? Je me demande même si c'est possible que ça puisse failed sans qu'il y ait une exception, considérant que firebase auth retourne des exeptions pour chaque erreur possible (genre complexité du password, courriel etc.). Pis ça fait pas en sorte qu'on vient faire de la vérification en double avec le true/false et les exceptions?

2023-02-26 17:04 UTC, chrichriGeorgie approved these changes

2023-02-28 04:17 UTC, cravethedave approved these changes

2023-02-28 04:40 UTC, merged