Plug scan et connexion dans le UI
LOG8970-Team14/figure_skating_jumps pull request #17
Opened 2023-02-27 01:11 UTC by chrichriGeorgie

-Fix permission
-See device list (à jour aux 10 sec)
-Connect with device in list

2023-02-27 03:32 UTC, Ch0ufleur requested changes

2023-02-27 03:32 UTC, Ch0ufleur commented on android/app/src/main/kotlin/com/example/figure_skating_jumps/XsensDotDeviceCB.kt
>  class XsensDotDeviceCB: XsensDotDeviceCallback {
Je trouve que le nom de la classe est pas significatif car l'abréviation CB m'est inconnue

2023-02-27 03:32 UTC, Ch0ufleur commented on android/app/src/main/res/values/strings.xml
> +    <string name="devices_permission_message">Afin de détecter et de communiquer avec les XSens DOT, l\'application nécessite que d\'avoir accès aux appareils à proximité. Vous pouvez activer la perm
```suggestion
    <string name="devices_permission_message">Afin de détecter et de communiquer avec les XSens DOT, l\'application nécessite l\'accès aux appareils à proximité. Vous pouvez activer la permission d\'appareil à proximité dans les paramètres de l\'appareil.</string>

```

2023-02-27 03:32 UTC, Ch0ufleur commented on lib/services/x_sens_dot_connection.dart
> +  Future<bool> connect(BluetoothDevice bluetoothDevice) async {
Future<bool> mais la valeur booleéene n'est pas récupérée et la fonction n'est pas awaitée dans le connextion_new_xsens_dialog

2023-02-27 03:32 UTC, Ch0ufleur commented on lib/services/x_sens_dot_connection.dart
> +  Future<bool> disconnect() async {
Future<bool> mais la valeur booleéene n'est pas récupérée et la fonction n'est pas appelée dans le configure_x_sens_dialog (ligne 60)

2023-02-27 03:32 UTC, Ch0ufleur commented on lib/services/x_sens_dot_connection.dart
> +  Future<bool> disconnect() async {
Aussi elle n'est pas awaitée dans le configure_new_xsens_dot_dialog (lignes 253, 201)

2023-02-27 03:32 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
>      super.initState();
super.initState devrait être appelé en dernier

2023-02-27 03:32 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                _xSensDotConnectionService.disconnect();
should be async + awaited

2023-02-27 03:32 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                _xSensDotConnectionService.disconnect();
should be async and awaited

2023-02-27 03:32 UTC, Ch0ufleur commented on lib/widgets/screens/demo_connection_view.dart
> +  final XSensDotChannelService _xsensDotService = XSensDotChannelService();
```suggestion
  final XSensDotChannelService _xSensDotService = XSensDotChannelService();
```

2023-02-27 03:32 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                      _xSensDotConnectionService.connect(_devices[index]);
should be async and awaited

2023-02-27 21:38 UTC, chrichriGeorgie commented on lib/widgets/screens/demo_connection_view.dart
> +  final XSensDotChannelService _xsensDotService = XSensDotChannelService();
je touche pas à la page de demo, elle va être retiré sous peu

2023-02-28 04:10 UTC, cravethedave approved these changes

2023-02-28 04:40 UTC, merged