set frequency on Xsens Dot setup page
LOG8970-Team14/figure_skating_jumps pull request #19
Opened 2023-02-28 20:16 UTC by MrPuffs

2023-03-01 21:07 UTC, chrichriGeorgie requested changes

2023-03-01 21:07 UTC, chrichriGeorgie commented on lib/services/x_sens_dot_connection.dart
> +  static const _xSensChannel = MethodChannel('xsens-dot-channel');
Il n'est pas nécessaire d'ajouter l'objet MethodChannel ici, il est déjà défini dans le XSensDOTChannelService

2023-03-01 21:17 UTC, Ch0ufleur requested changes

2023-03-01 21:17 UTC, Ch0ufleur commented on android/app/src/main/kotlin/com/example/figure_skating_jumps/MainActivity.kt
> +        currentXSensDot?.setOutputRate(60)
Sinon possiblement considérer un ternaire si besoin de garder les deux cas

2023-03-01 21:17 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +  late String selectedRate = outputRate.last;
pas sur de comprendre le besoin d'avoir defaultFrequency en haut si on donne déjà une valeur par défaut à selectedRate

2023-03-01 21:17 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                    _xSensDotConnectionService.setRate(int.parse(selectedRate));
c'est une fonction async donc il faut la await et gérer le cas où il y aurait un problème côté UI

2023-03-01 21:17 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                onChanged: (String? value) {
```suggestion
                onChanged: (String? value) async {

```

2023-03-01 21:17 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                    _xSensDotConnectionService.setRate(int.parse(selectedRate));
```suggestion
                    await _xSensDotConnectionService.setRate(int.parse(selectedRate));

```

2023-03-01 21:17 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                items: outputRate.map<DropdownMenuItem<String>>((String value) {
On ne veut pas proposer à l'utilisateur une fréquence autre que 120 à mon avis, car c'est ce que le client demande. À la limite on pourrait mettre 60 mais je pense alors que le dropdown ne serait pas le meilleur contrôle; il faudrait mettre un deux radio button car on a seulement deux options.

Aussi si on propose plus qu'une fréquence l'utilisateur lambda ne saura pas nécessairement l'impact du choix ni laquelle choisir et pour quelle raison. Ma compréhension était qu'on imposait 120 dans tous les cas.

2023-03-01 21:17 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +          child: Container(),
probablement qu'il peut être enlevé oui

2023-03-01 21:17 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +      _xSensDotConnectionService.setRate(defaultFrequency);
en effet l'utilisateur est obligé de faire le choix juste après donc je pense pas qu'on ait à mettre une valeur si c'est pour la changer direct après, ça enlèverait aussi le besoin d'utiliser defaultfrequency et ca sauverait une variable

2023-03-01 21:18 UTC, Ch0ufleur commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                ),
probablement que oui à terme, mais si on force 120hz il n'y aurait même plus lieux de faire une choix ici donc à voir si on aurait des dropdown ailleurs

2023-03-03 18:09 UTC, MrPuffs commented on android/app/src/main/kotlin/com/example/figure_skating_jumps/MainActivity.kt
> +        currentXSensDot?.setOutputRate(60)
changed

2023-03-03 18:10 UTC, MrPuffs commented on lib/services/x_sens_dot_connection.dart
> +  }
non je l'ai changer de classe

2023-03-03 18:11 UTC, MrPuffs commented on lib/services/x_sens_dot_connection.dart
> +  }
je vais la redéplacer

2023-03-03 18:11 UTC, MrPuffs commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +  static const int defaultFrequency = 60;
pour l'instant ça va être 60 mais après le recording on aura juste à changer le const

2023-03-03 18:11 UTC, MrPuffs commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +  List<String> outputRate = ["20", "30", "60"];
same

2023-03-03 18:12 UTC, MrPuffs commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +          child: Container(),
ouais un oublie sorry

2023-03-03 18:13 UTC, MrPuffs commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                ),
ça va disparaitre

2023-03-03 18:14 UTC, MrPuffs commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +      _xSensDotConnectionService.setRate(defaultFrequency);
ici c'est pour connecter un device qui n'a jamais été connecté avant

2023-03-03 18:15 UTC, MrPuffs commented on lib/services/x_sens_dot_connection.dart
> +  static const _xSensChannel = MethodChannel('xsens-dot-channel');
changed

2023-03-03 18:19 UTC, MrPuffs commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +  late String selectedRate = outputRate.last;
removed

2023-03-03 18:20 UTC, MrPuffs commented on lib/widgets/dialogs/connection_new_xsens_dot_dialog.dart
> +                items: outputRate.map<DropdownMenuItem<String>>((String value) {
changed

2023-03-06 01:48 UTC, Ch0ufleur requested changes

2023-03-06 01:48 UTC, Ch0ufleur commented on android/app/src/main/kotlin/com/example/figure_skating_jumps/MainActivity.kt
> +        result.success(false)
Devrait utiliser result.error
Sinon conceptuellement on dit que ça success avec une valeur de False c'est un non-sens

2023-03-06 01:48 UTC, Ch0ufleur commented on lib/services/x_sens_dot_channel_service.dart
> +          .invokeMethod('setRate', <String, dynamic>{'rate': rate});
Ici peu importe ce que invokeMethod va retourner (que ce soit true ou false), la fonction va toujours retourner True parce qu'on ne vérifie pas le résultat de call avec await

2023-03-06 15:25 UTC, Ch0ufleur approved these changes

2023-03-06 15:26 UTC, chrichriGeorgie approved these changes

2023-03-06 15:27 UTC, merged