mock de la page de connection
LOG8970-Team14/figure_skating_jumps pull request #21
Opened 2023-03-06 19:04 UTC by MrPuffs

2023-03-06 21:04 UTC, chrichriGeorgie requested changes

2023-03-06 21:24 UTC, Ch0ufleur requested changes

2023-03-06 21:24 UTC, Ch0ufleur commented on lib/widgets/screens/login_view.dart
> +  String _coachPassword = '';
dans cette page-là ce sont pas nécessairement des coach - la page de login sert aussi pour les athlètes, il faudrait que les noms des variables le reflètent

2023-03-06 21:24 UTC, Ch0ufleur commented on lib/widgets/screens/login_view.dart
> +        body: SingleChildScrollView(
ça prend un gesturedetector encadrant pour enlever le focus du clavier si on clique à l'extérieur d'un champ de texte

2023-03-06 21:24 UTC, Ch0ufleur commented on lib/widgets/screens/login_view.dart
> +                height: 120,
la hauteur devrait être 100 pour être cohérente avec la page de création de compte coach

2023-03-06 21:24 UTC, Ch0ufleur commented on lib/widgets/screens/login_view.dart
> +            const SizedBox(height: 150),
pt s'assurer que t'a pas besoin d'un media query comme dans la page coach pour être sûr que tout s'adapte à la taille de n'importe quel appareil au lieu de mettre 150 hardcodé

2023-03-06 21:24 UTC, Ch0ufleur commented on lib/widgets/screens/login_view.dart
> +  final _personalInfoKey = GlobalKey<FormState>();
plutôt connectionInfoKey (dans le cas du coach c'était le personnalInfo parce que c'était le but du premier écran - ici ya pas de distinction)

2023-03-06 21:24 UTC, Ch0ufleur commented on lib/widgets/screens/login_view.dart
> +                                          const CoachAccountCreationView()),
Utiliser les routes nommées dans main.dart
=> pushReplacementNamed

2023-03-06 22:53 UTC, MrPuffs commented on lib/widgets/screens/coach_account_creation_view.dart
> +                      MaterialPageRoute(
okay cool je savais pas qu'on pouvais faire ça !
Changed

2023-03-06 22:53 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +                // height: 200,
removed

2023-03-06 22:57 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +                            },
je suis pas tant d'accord la dessus c'est un mock live je fais juste le UI mais genre demain je vais linker les actions avec les bonnes fonctions. J'ai juste séparé la PR en 2 en gros mais ça va se faire bientôt

2023-03-06 22:59 UTC, MrPuffs commented on lib/constants/lang_fr.dart
> +const String createAccount = "Me créer un compte";
tu as raison c'était un genre de mélange de francais pis d'anglais sorry

2023-03-06 23:01 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +  String _coachPassword = '';
changed

2023-03-06 23:02 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +        body: SingleChildScrollView(
added

2023-03-06 23:03 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +                height: 120,
dans la maquette il avait l'air plus gros mais je vais le mettre à 100 pas de problème

2023-03-06 23:07 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +            const SizedBox(height: 150),
j'ai mis un widget center à la place

2023-03-06 23:07 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +                                          const CoachAccountCreationView()),
changed

2023-03-06 23:08 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +  final _personalInfoKey = GlobalKey<FormState>();
changed

2023-03-07 00:40 UTC, Ch0ufleur reviewed
va juste falloir faire passer les deux checks

2023-03-07 00:42 UTC, chrichriGeorgie commented on lib/widgets/screens/login_view.dart
> +                            },
Ok lorsque les autres commentaires seront fix on pourra approuve et merge. Par contre, idéalement lorsque le back-end est déjà fait, je pense que c'est mieux au niveau des processus et du suivi de l'avancement de faire une merge request pour ajouter une fonctionnalité complète. Donc si on merge, je m'attends à ce que la MR de plug arrive mardi.

(Tu peux resolve le commentaire lorsque tu auras vu le message)

2023-03-07 00:49 UTC, chrichriGeorgie requested changes

2023-03-07 00:49 UTC, chrichriGeorgie commented on lib/widgets/screens/login_view.dart
> +                                    },
Je pense que GitHub m'as joué un tour sur mes commentaires sur les validators tantôt en terme de code montré et vu que j'ai pas donné assez de contexte, il y a eu miscommunication. Lorsque je parlais de code non approprié,  je voulais juste parler de la validation du format de mail et de la longueur du mot de passe. 
Désolé pour le travail en double, mais il faudrait que tu remettes le email et password validators mais juste pour vérifier que les champs ne sont pas vide/null, sinon ça n'empêche pas d'envoyer la requête alors que des champs sont vides.

Je propose une fonction unique (genre textFieldValidator ou quelque chose du genre) qui ferait le empty et le null check mais sans plus.

2023-03-07 16:58 UTC, MrPuffs commented on lib/widgets/screens/login_view.dart
> +                                    },
okay mais je vais ajouter ça dans la prochaine PR je pense que ça fait plus de sens

2023-03-07 17:09 UTC, chrichriGeorgie commented on lib/widgets/screens/login_view.dart
> +                                    },
Ok, je vais approuve puisque c'est prévu pour la prochaine pr

2023-03-07 17:11 UTC, merged