Started custom exceptions
LOG8970-Team14/figure_skating_jumps pull request #24
Opened 2023-03-07 21:05 UTC by cravethedave

2023-03-07 21:19 UTC, chrichriGeorgie requested changes

2023-03-07 21:19 UTC, chrichriGeorgie commented on lib/services/user_client.dart
> +          rethrow;
A mettre dans une fonction et faire le check au sign up aussi

2023-03-07 21:19 UTC, chrichriGeorgie commented on lib/constants/lang_fr.dart
> +const String nullUserException = "L'utilisateur n'a pas été trouvé.";
À voir avec @Ch0ufleur  pour les messages finaux

2023-03-07 21:30 UTC, chrichriGeorgie commented on lib/services/user_client.dart
> +          rethrow;
Finalement, changer le switch pour des catchs spécifiques (y'a des sous exceptions à FirebaseAuthException normalement): https://www.oreilly.com/library/view/mastering-firebase-for/9781788624718/16c15a62-ecc4-4d8f-a232-52e3cb04816d.xhtml

2023-03-07 21:42 UTC, cravethedave commented on lib/constants/lang_fr.dart
> +const String nullUserException = "L'utilisateur n'a pas été trouvé.";
On peut les laisser comme placeholder for now et plus tard les changer quand on commence a les use dans le UI
that was my idea at least

2023-03-07 21:42 UTC, cravethedave commented on lib/services/user_client.dart
> +          rethrow;
J'ai rien trouve sur comment y acceder dans Dart et la communaute semble faire des switchs.

2023-03-08 00:25 UTC, Ch0ufleur commented on lib/exceptions/weak_password_exception.dart
> +  }
je comprend pas vraiment à quoi toutes ces exceptions servent si le UI ne permet pas d'envoyer des données invalides compte tenu qu'on implémente pas la sécurité

2023-03-08 00:25 UTC, Ch0ufleur commented on lib/services/user_client.dart
> +          rethrow;
la gestion d'exception c'est pas juste censé être une série de catch un après l'autre du plus spécifique au plus général?

2023-03-08 03:09 UTC, Ch0ufleur approved these changes

2023-03-08 03:10 UTC, chrichriGeorgie approved these changes

2023-03-08 03:11 UTC, merged