page d'acquisitions précédentes
LOG8970-Team14/figure_skating_jumps pull request #31
Opened 2023-03-15 00:15 UTC by MrPuffs

2023-03-15 02:02 UTC, chrichriGeorgie commented on android/app/src/main/kotlin/com/example/figure_skating_jumps/channels/event_channels/BluetoothPermissionStreamHandler.kt
> +    }
Y'a vraiment beaucoup de fichier qui sont comme ça. Peux-tu vérifier que tu as les même fin de ligne que ce qui est sur git (CRLF vs LF si je ne me trompe pas. Il y a une commande à appliquer dans git pour éviter le problème)

2023-03-15 02:36 UTC, cravethedave requested changes
SVP change les endlines pour que ce soit comme le standard actuel. Ce sera plus lisible.

2023-03-15 03:04 UTC, chrichriGeorgie requested changes

2023-03-15 03:04 UTC, chrichriGeorgie commented on lib/models/capture.dart
> +    }
Cette fonction ne devrait pas exister, l'initialisation des sauts devrait se faire dans le factory Capture.fromFirestore

2023-03-15 03:04 UTC, chrichriGeorgie commented on lib/services/capture_client.dart
> +          .set({"jumps": capture.jumps}, SetOptions(merge: true));
Niveau lisibilité c'est assez moyen de mettre deux await de 4 lignes comme paramètre d'une fonction

2023-03-15 04:27 UTC, Ch0ufleur requested changes

2023-03-15 04:27 UTC, Ch0ufleur commented on lib/widgets/layout/captures_tab.dart
> +                    borderRadius: BorderRadius.circular(10)),
moyen de sortir ça dans une fonction ou un mini widget qui créer un petit rond avec la couleur en paramètre, vu que c'est le même code juste au dessus on éviterait de répéter

2023-03-15 04:27 UTC, Ch0ufleur commented on lib/widgets/layout/options_tab.dart
> +    return const Center(
Stateless, même raison, mais ça on pourra le changer pour chaque page spécifique rendu à ces tâches-là

2023-03-15 04:27 UTC, Ch0ufleur commented on lib/widgets/layout/progression_tab.dart
> +  Widget build(BuildContext context) {
Stateless, même raison, mais ça on pourra le changer pour chaque page spécifique rendu à ces tâches-là.
Mais change pas ce fichier-ci spécifiquement parce que j'en ai commencé un autre dans ma tâche avec les graphiques donc je vais m'Arranger pour les merger ensemble une fois ta MR mergée

2023-03-15 04:27 UTC, Ch0ufleur commented on lib/widgets/screens/acquisitions_view.dart
> +                        fontWeight: FontWeight.bold))),
on peut utiliser le widget PageTitle que j'ai créé exprès (widgets/titles)

2023-03-15 04:27 UTC, Ch0ufleur commented on lib/widgets/screens/acquisitions_view.dart
> +              containerWight: MediaQuery.of(context).size.width - 32,
si on fait un media query ça va être très énorme sur une tablette donc il faudrait lui donner une largeur fixe je pense, pas vraiment d'autre choix mais je suis ouvert aux suggestions

2023-03-15 04:27 UTC, Ch0ufleur commented on lib/widgets/screens/acquisitions_view.dart
> +                    )),
on pourrait sortir le style dans une variable locale

2023-03-15 04:27 UTC, Ch0ufleur commented on lib/widgets/screens/acquisitions_view.dart
> +                  )
le ternaire est sur deux widget identiques, donc en fait il devrait être au niveau du child du expanded, quitte à perdre le const

2023-03-15 04:27 UTC, Ch0ufleur commented on lib/widgets/screens/acquisitions_view.dart
> +                        _optionsTab,
vu qu'ils ne sont pas réutilisées, pas besoin de faire des variables en haut de la classe, on peut direct mettre genre const CaptureTab(), etc.

2023-03-15 18:41 UTC, MrPuffs commented on android/app/src/main/kotlin/com/example/figure_skating_jumps/channels/event_channels/BluetoothPermissionStreamHandler.kt
> +    }
Mon éditeur est en CRLF so je sais pas trop pourquoi ça fait ça

2023-03-15 18:43 UTC, MrPuffs commented on lib/models/capture.dart
> +    }
La fonction existe parce que je dois await les sauts. Comme tu ne peux pas await dans un constructeur j'ai fait cette fonction

2023-03-15 18:45 UTC, MrPuffs commented on lib/services/capture_client.dart
> +          .set({"jumps": capture.jumps}, SetOptions(merge: true));
je l'ai store dans une variable

2023-03-15 18:47 UTC, MrPuffs commented on lib/main.dart
> +      _asyncMethod();
fait mais la fonction va partir eventuellement

2023-03-15 18:49 UTC, chrichriGeorgie commented on android/app/src/main/kotlin/com/example/figure_skating_jumps/channels/event_channels/BluetoothPermissionStreamHandler.kt
> +    }
C'est peut-être tes git config, checke dont ça

2023-03-15 18:54 UTC, chrichriGeorgie commented on lib/models/capture.dart
> +    }
Yeah fair enough, si ça ne brise rien, il faudrait que le constructeur fromFirestore soit privé dans ce cas et que tu renomme la fonction à createFromFirestore

2023-03-15 18:58 UTC, MrPuffs commented on lib/main.dart
> +              child: const Text('Acquisitions')),
Dans ce cas, la page prend un paramètre en constructeur. Le paramètre va dépendre donc je vois pas comment ça pourrait marcher, si il faut construire l'objet après avoir cliquer sr le user

2023-03-15 18:59 UTC, MrPuffs commented on lib/utils/time_converter.dart
> +}
je vais garder ma fonction puisqu'elle fonctionne

2023-03-15 19:00 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +      DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day);
ça ne fonctionnerait pas parce que je veux que les heures, minutes, secondes,... soient à 0

2023-03-15 19:03 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +            height: MediaQuery.of(context).size.height - 300,
j'avais essayer mais ça marche pas il faut une valeur pour le height

2023-03-15 19:06 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +            height: MediaQuery.of(context).size.height - 300,
sinon ça prend le screen au complet

2023-03-15 19:06 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +                final item = widget.captures[index];
added

2023-03-15 19:06 UTC, Ch0ufleur commented on lib/main.dart
> +              child: const Text('Acquisitions')),
https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments

Navigator.pushNamed(
      context,
      nomdelaroute,
      arguments:Skater()',
    );

dans le widget:

final args = ModalRoute.of(context)!.settings.arguments as Skater;

qqch de même, sinon on peut discuter si on veut toujours utiliser des named route ou pas

2023-03-15 19:07 UTC, Ch0ufleur commented on lib/widgets/layout/captures_tab.dart
> +            height: MediaQuery.of(context).size.height - 300,
je pensais que c'était ce qu'on voulait ici

2023-03-15 19:08 UTC, Ch0ufleur commented on lib/widgets/layout/captures_tab.dart
> +      DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day);
oui mais voir mon commentaire plus bas, je pense pas que ce soit la façon idéale

2023-03-15 19:08 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +                                  fontSize: 26,
pourquoi ? J'aime mon 26 :)

2023-03-15 19:10 UTC, chrichriGeorgie commented on lib/widgets/layout/captures_tab.dart
> +      DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day);
Mais techniquement on aurait pas besoin de cet objet si on tri et group le contenu de la liste par date.

2023-03-15 19:10 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +                          : Container(),
changed

2023-03-15 19:10 UTC, Ch0ufleur commented on lib/widgets/layout/captures_tab.dart
> +                                  fontSize: 26,
C'Est un truc que j'avais appris dans mon stage en UX:

https://uxplanet.org/everything-you-should-know-about-8-point-grid-system-in-ux-design-b69cb945b18d

2023-03-15 19:12 UTC, chrichriGeorgie commented on lib/main.dart
> +      _asyncMethod();
Yeah mais ça fait pas super professionnel d'avoir un nom aussi peu significatif at some point dans notre git history. Pis même si ce sera à enlever, on ne sait pas encore qui devra enlever le bloc de code donc ce serait bien de savoir en un coup d'oeil ce que fait la fonction.

2023-03-15 19:13 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +                                  children: List.generate(6, (index) {
changed

2023-03-15 19:14 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +        children: List.generate(6, (index) {
changed

2023-03-15 19:15 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +                    borderRadius: BorderRadius.circular(10)),
c'est un code de 6 lignes qui est présent 2 fois dans le code je vois pas trop la nécessité de faire ça perso

2023-03-15 19:20 UTC, chrichriGeorgie commented on lib/utils/time_converter.dart
> +}
Je suis pas d'accord vu qu'on veut livrer du code de qualité sans smells. Effectivement la fonction marche mais en même temps qu'il existe déjà des fonctions qui font la même chose, c'est clairement un Reinvent The Wheel antipattern que tu as surement vu dans le cours d'architecture cette session.

2023-03-15 19:21 UTC, chrichriGeorgie commented on lib/utils/time_converter.dart
> +}
Mais bon, si tout le monde approuve que tu ne le change pas, je ne me batterai pas plus que ça

2023-03-15 19:28 UTC, chrichriGeorgie commented on lib/widgets/layout/captures_tab.dart
> +                    borderRadius: BorderRadius.circular(10)),
C'est still de la duplication tho, pis ce pourrait peut-être être réuitliser pour la progression vu pour pour la page de rétroaction

2023-03-15 20:02 UTC, Ch0ufleur commented on lib/utils/time_converter.dart
> +}
J'insisterais pour le changer aussi compte tenu des points que Christophe apporte

2023-03-15 20:46 UTC, MrPuffs commented on lib/widgets/screens/acquisitions_view.dart
> +                        fontWeight: FontWeight.bold))),
changed

2023-03-15 20:48 UTC, MrPuffs commented on lib/widgets/screens/acquisitions_view.dart
> +              containerWight: MediaQuery.of(context).size.width - 32,
ben la ça va poser problème sur certain téléphone, non ?

2023-03-15 20:48 UTC, MrPuffs commented on lib/widgets/screens/acquisitions_view.dart
> +                  )
changed

2023-03-15 20:50 UTC, Ch0ufleur commented on lib/widgets/screens/acquisitions_view.dart
> +              containerWight: MediaQuery.of(context).size.width - 32,
Oui... faudrait réfléchir à une solution qui marche tjrs... Pt un max width et un min width? I dunno

2023-03-15 20:51 UTC, MrPuffs commented on lib/widgets/screens/acquisitions_view.dart
> +                        _optionsTab,
changed

2023-03-15 20:58 UTC, MrPuffs commented on lib/models/capture.dart
> +    }
changed

2023-03-15 20:59 UTC, MrPuffs commented on lib/main.dart
> +      _asyncMethod();
yeah yeah it has been changed

2023-03-15 21:05 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +            height: MediaQuery.of(context).size.height - 300,
non capture_tab c<est juste la parti sous la barre de navigation (captures/progression/options)

2023-03-15 21:19 UTC, MrPuffs commented on lib/widgets/layout/options_tab.dart
> +    return const Center(
changed

2023-03-15 21:19 UTC, MrPuffs commented on lib/widgets/layout/progression_tab.dart
> +  Widget build(BuildContext context) {
Okay

2023-03-15 21:31 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +                    borderRadius: BorderRadius.circular(10)),
okay c'est good je l'ai changer!

2023-03-15 21:41 UTC, MrPuffs commented on lib/utils/time_converter.dart
> +}
ben j'ai essayer mais ça marche pas tant bien parce que ça affiche toujours 2 chiffres exemple: 02m 34sec. pis c'est laid

2023-03-15 21:42 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +  final dateDisplayFormat = DateFormat('dd/MM/yyyy');
malheureusement ça peut pas être un stateless widget parce qu'il y a une variable non constante

2023-03-15 21:45 UTC, Ch0ufleur commented on lib/widgets/layout/captures_tab.dart
> +  final dateDisplayFormat = DateFormat('dd/MM/yyyy');
Laquelle?

2023-03-15 22:21 UTC, MrPuffs commented on lib/constants/lang_fr.dart
> +const String toeAbbreviation = "T";
honnêtement je vois pas comment vous voyez ça avec un enum parce que je peux pas itéré sur un enum. genre je vois pas

2023-03-15 22:28 UTC, chrichriGeorgie commented on lib/constants/lang_fr.dart
> +const String toeAbbreviation = "T";
https://stackoverflow.com/a/64887179

C'est possible d'itérer sur un enum d'après ce lien

2023-03-15 23:13 UTC, Ch0ufleur commented on lib/widgets/layout/captures_tab.dart
> +            height: MediaQuery.of(context).size.height - 300,
C'est ça mais si on fait un expanded ça va prendre l'espace jusqu'en bas juste à partir de cet endroit là... jvais essayer de le changer voir

2023-03-16 00:55 UTC, Ch0ufleur commented on lib/utils/time_converter.dart
> +}
ya sûrement moyen de l'adapter? genre gosser avec le padLeft

2023-03-16 13:29 UTC, MrPuffs commented on lib/widgets/screens/acquisitions_view.dart
> +                    )),
changed

2023-03-16 14:46 UTC, MrPuffs commented on lib/models/capture.dart
> +  final List<int> _jumpTypeCount = [0, 0, 0, 0, 0, 0];
changed

2023-03-16 15:00 UTC, MrPuffs commented on lib/main.dart
> +              child: const Text('Acquisitions')),
done

2023-03-16 20:43 UTC, MrPuffs commented on lib/widgets/layout/captures_tab.dart
> +  final dateDisplayFormat = DateFormat('dd/MM/yyyy');
maintenant c'est stateless

2023-03-16 21:29 UTC, chrichriGeorgie requested changes

2023-03-16 21:29 UTC, chrichriGeorgie commented on lib/widgets/layout/captures_tab.dart
> +            height: MediaQuery.of(context).size.height - 300,
On le laisse en media query ou en expanded finalement? Y'a comme pas de résolution

2023-03-16 21:29 UTC, chrichriGeorgie commented on lib/widgets/screens/acquisitions_view.dart
> +    //WidgetsBinding.instance.addPostFrameCallback((_) => _loadCapturesData());
Code comment à remove s'il n'est plus nécessaire

2023-03-16 22:15 UTC, MrPuffs commented on lib/widgets/screens/acquisitions_view.dart
> +    //WidgetsBinding.instance.addPostFrameCallback((_) => _loadCapturesData());
removed

2023-03-16 22:25 UTC, Ch0ufleur approved these changes

2023-03-16 22:28 UTC, chrichriGeorgie approved these changes

2023-03-16 22:37 UTC, cravethedave approved these changes

2023-03-16 22:37 UTC, merged