46 user preferences
LOG8970-Team14/figure_skating_jumps pull request #36
Opened 2023-03-20 16:57 UTC by cravethedave

2023-03-22 18:16 UTC, MrPuffs commented on lib/models/db_models/abstract_local_db_object.dart
>    }
Je suis pas sur de l'utilité d'une class abstraite avec un type optionnel. Ça brise un peu le principe de la classe.

2023-03-22 18:16 UTC, MrPuffs commented on lib/models/db_models/abstract_local_db_object.dart
>    }
Ici je propose de set le id dans le constructeur et non d'avoir une fonction pour reset le ID

2023-03-22 21:15 UTC, cravethedave commented on lib/models/db_models/abstract_local_db_object.dart
>    }
Le problème avec le id ici est qu'on ne connait pas le id d'un objet si on ne l'a pas encore mis dans la base de données. En conclusion, le id doit être nullable pour qu'on puisse envoyer l'objet à la DB.

Resolve if you agree.

2023-03-22 21:17 UTC, cravethedave commented on lib/models/db_models/abstract_local_db_object.dart
>    }
Ce problème est directement lié au problème plus haut. Resolve too if you agree.

2023-03-23 02:47 UTC, chrichriGeorgie approved these changes

2023-03-23 02:47 UTC, chrichriGeorgie commented on python_analysis/anthony/expected_output.txt
> +    jmp 14:71 2090ish
Fichier accidentel, ça me dérange pas qu'on le laisse vu qu'il était sensé arriver dans une MR prochaine très bientôt. Si vous tenez à ce qu'il soit enlevé dites le à David :)

2023-03-23 03:19 UTC, Ch0ufleur requested changes

2023-03-23 03:19 UTC, Ch0ufleur commented on lib/services/manager/device_names_manager.dart
> +  static final DeviceNamesManager _userPreferencesManager =
change variable name

2023-03-23 03:19 UTC, Ch0ufleur commented on lib/services/x_sens/x_sens_dot_connection_service.dart
> +    return _currentXSensDevice!;
ça revient pas à faire
return _currentXSensDevice;   

?

2023-03-23 14:07 UTC, Ch0ufleur approved these changes

2023-03-23 14:11 UTC, merged