Improve firebase client
LOG8970-Team14/figure_skating_jumps pull request #42
Opened 2023-03-24 20:17 UTC by chrichriGeorgie

- Get by id (capture, jump)
- Removed unecessary ref to firestore
- Create jump
- Modify jump
- Remove coach

2023-03-25 14:08 UTC, Ch0ufleur commented on lib/services/capture_client.dart
> +  Future<Capture> getCaptureByID({required String uid}) async {
uID

2023-03-25 14:08 UTC, Ch0ufleur commented on lib/services/capture_client.dart
> +      return await Capture.createFromFireBase(uid, captureInfo);
Firebase

(sans le b majuscule)

2023-03-25 14:08 UTC, Ch0ufleur commented on lib/widgets/views/athlete_view.dart
> +    _futureCaptures ??= skater?.loadCapturesData(); //TODO load before
tu les loaderais au moment de cliquer sur le nom de l'athlète avant d'envoyer le Skater en paramètre?

2023-03-25 19:33 UTC, Ch0ufleur approved these changes

2023-03-25 21:10 UTC, cravethedave requested changes

2023-03-25 21:10 UTC, cravethedave commented on lib/models/skating_user.dart
> +  late List<String> _coachesID = [];
Pourquoi on garde les ids et les classes? Idéalement on ne garde que les ids et on va chercher ce qu'on a besoin when needed.

2023-03-25 21:10 UTC, cravethedave commented on lib/services/capture_client.dart
> +      rethrow;
Cette fonction ne devrait pas exister, son code devrait être dans createJump plus haut. C'est toujours le même use case.

2023-03-26 01:02 UTC, chrichriGeorgie commented on lib/models/skating_user.dart
> +  late List<String> _coachesID = [];
Un refactor sera fait la remise beta

2023-03-26 01:11 UTC, chrichriGeorgie commented on lib/services/capture_client.dart
> +      rethrow;
La majorité est en désaccord avec le commentaire

2023-03-26 01:12 UTC, cravethedave approved these changes

2023-03-26 01:12 UTC, merged