38 File adding works
LOG8970-Team14/figure_skating_jumps pull request #46
Opened 2023-03-26 03:11 UTC by cravethedave

2023-03-26 13:47 UTC, Ch0ufleur approved these changes

2023-03-26 14:52 UTC, MrPuffs commented on python_analysis/analysis.py
> +    end = jump.end * (8333 / SEC_TO_MS_RATIO)
maybe une constante pour 8333?

2023-03-26 14:52 UTC, MrPuffs approved these changes

2023-03-26 15:18 UTC, chrichriGeorgie commented on python_analysis/analysis.py
> +    end = jump.end * (8333 / SEC_TO_MS_RATIO)
je seconde la dessus

2023-03-26 15:20 UTC, chrichriGeorgie requested changes
J'ai mis requested change mais si tut trouves que la constante pour 8333 n'est pas pertinent. Tu peux merge @cravethedave

2023-03-26 15:20 UTC, chrichriGeorgie commented on python_analysis/analysis.py
> +    end = jump.end * (8333 / SEC_TO_MS_RATIO)
je seconde la dessus

2023-03-27 00:09 UTC, cravethedave commented on python_analysis/analysis.py
> +    end = jump.end * (8333 / SEC_TO_MS_RATIO)
Done, je l'avais miss

2023-03-27 00:18 UTC, merged