87 video sqlite
LOG8970-Team14/figure_skating_jumps pull request #51
Opened 2023-03-28 03:00 UTC by cravethedave

2023-03-28 03:21 UTC, chrichriGeorgie requested changes

2023-03-28 03:21 UTC, chrichriGeorgie commented on lib/models/db_models/local_capture.dart
> +  final String _path;
J'appellerais ça videoPath pour distinguer avec le fichier de données

2023-03-28 03:21 UTC, chrichriGeorgie commented on lib/models/db_models/local_capture.dart
> +  final String _path;
Et je sais pas si pertinent mais si on veux garder le path du fichier de donnée local

2023-03-28 03:59 UTC, cravethedave commented on lib/models/db_models/local_capture.dart
> +  final String _path;
> Et je sais pas si pertinent mais si on veux garder le path du fichier de donnée local

Can you elaborate

2023-03-29 02:38 UTC, Ch0ufleur commented on lib/models/db_models/local_capture.dart
> +  final String _path;
+1

2023-03-29 02:41 UTC, Ch0ufleur commented on lib/services/manager/local_captures_manager.dart
> +  static const String pathToFiles = "testing";
testing c'est voulu?

2023-03-29 02:42 UTC, Ch0ufleur approved these changes

2023-03-29 13:40 UTC, chrichriGeorgie commented on lib/models/db_models/local_capture.dart
> +  final String _path;
fixed

2023-03-29 13:42 UTC, chrichriGeorgie commented on lib/services/manager/local_captures_manager.dart
> +  static const String pathToFiles = "testing";
La varible est non utilisée pour l'instant, je pense que ça va venir avec le flux de capture de faire l'enregistrement de la video en BD

2023-03-29 13:43 UTC, chrichriGeorgie approved these changes

2023-03-29 13:45 UTC, merged