79 helper page thomas
LOG8970-Team14/figure_skating_jumps pull request #57
Opened 2023-03-31 16:13 UTC by MrPuffs

Gros PR de texte. Dites moi si vous voulez que j'ajoute des blocs. Je pense avoir couvert l'essenciel mais j'ai peut-être oublié dequoi

2023-03-31 18:05 UTC, chrichriGeorgie requested changes

2023-03-31 18:05 UTC, chrichriGeorgie commented on lib/widgets/dialogs/helper_dialog.dart
> +                  GestureDetector(
Ce lien stack overflow recommandais d'utiliser un InkWell widget à la place d'un GestureDetector puisque le InkWell peut montrer un effet visuel au user lorsqu'il interagit avec le widget

2023-03-31 18:05 UTC, chrichriGeorgie commented on lib/widgets/dialogs/helper_dialog.dart
> +    return AlertDialog(
Pourquoi ne pas utiliser un SimpleDialog s'il il n'y a pas de bouton d'action?

2023-03-31 18:05 UTC, chrichriGeorgie commented on lib/widgets/layout/scaffold/ice_drawer_menu.dart
> +                                                UserClient().signOut();
signOut est async, il faudrait donc le await

2023-03-31 18:05 UTC, chrichriGeorgie commented on lib/widgets/layout/scaffold/ice_drawer_menu.dart
> +                          color: discreetText,
Je ne sais pas si niveau UI/UX on ne voudrait pas mettre le bouton d'aide dans la même row que le bouton de compte et de deconnexion. Genre collé à gauche ou à droite du bouton de compte

2023-04-01 00:52 UTC, cravethedave commented on lib/enums/helper_subject.dart
> +      "Afin de prendre une nouvelle capture, il suffit de cliquer sur le bouton \"Capturer\" de la liste des captures. Si le support vidéo n'est pas activé, il est possible de l'activer dans les para
Il y a une couple d'erreurs de francais dans les textes.
Also, dans skaterInfo et modificationInfo, tu mentionnes "le bouton suivant", il y a-t-il une image pour indiquer quel est le bouton? Ou est ce que c'est directement sur la bonne page avec un seul bouton de possible?

2023-04-01 03:58 UTC, Ch0ufleur commented on lib/enums/helper_subject.dart
> +      "Afin de prendre une nouvelle capture, il suffit de cliquer sur le bouton \"Capturer\" de la liste des captures. Si le support vidéo n'est pas activé, il est possible de l'activer dans les para
Pour connecter un XSens Dot, assurez-vous que la batterie est pleine, cliquez sur la barre de statu*t* du senseur ou le bouton suivant.\n\nVous *p*ourrez ainsi connecter un XSens Dot déjà enregistr*é* ou un *nouvel appareil* avec le bouton au bas de la page.

Cependant, les vidéos ne sont accessible*s* que sur l'appareil utilisé.

2023-04-01 04:00 UTC, Ch0ufleur commented on lib/widgets/dialogs/helper_dialog.dart
> +          height: 500,
note mentale que ca va être changer possiblement pour l,adaptation tablette

2023-04-01 04:08 UTC, Ch0ufleur requested changes

2023-04-01 04:08 UTC, Ch0ufleur commented on lib/widgets/dialogs/helper_dialog.dart
> +                                text: "Me diriger sur la page",
à mettre dans lang_fr.dart

2023-04-01 04:09 UTC, Ch0ufleur commented on lib/widgets/layout/scaffold/ice_drawer_menu.dart
> +                          color: discreetText,
non je le laisserais là

2023-04-01 15:57 UTC, MrPuffs commented on lib/enums/helper_subject.dart
> +      "Afin de prendre une nouvelle capture, il suffit de cliquer sur le bouton \"Capturer\" de la liste des captures. Si le support vidéo n'est pas activé, il est possible de l'activer dans les para
changed

2023-04-01 15:57 UTC, MrPuffs commented on lib/widgets/dialogs/helper_dialog.dart
> +                                text: "Me diriger sur la page",
changed

2023-04-01 16:00 UTC, MrPuffs commented on lib/widgets/layout/scaffold/ice_drawer_menu.dart
> +                                                UserClient().signOut();
added

2023-04-01 16:05 UTC, MrPuffs commented on lib/widgets/dialogs/helper_dialog.dart
> +    return AlertDialog(
effectivement je l'ai changé

2023-04-01 16:06 UTC, MrPuffs commented on lib/widgets/dialogs/helper_dialog.dart
> +                  GestureDetector(
okay bonne idée !

2023-04-01 18:04 UTC, chrichriGeorgie approved these changes

2023-04-02 02:31 UTC, Ch0ufleur approved these changes

2023-04-02 02:31 UTC, merged