66 forgot pwd button
LOG8970-Team14/figure_skating_jumps pull request #65
Opened 2023-04-01 20:56 UTC by cravethedave

2023-04-01 21:35 UTC, chrichriGeorgie approved these changes

2023-04-01 23:59 UTC, Ch0ufleur requested changes

2023-04-01 23:59 UTC, Ch0ufleur commented on lib/widgets/views/forgot_password_view.dart
> +                                    }
ça sert à rien d'avoir un Widget form si tu as pas un FormKey associé que tu peux call genre key.currentState.validate au moment de soumettre pour trigger le validator sur le inputField -> hmu si c'Est pas clair

2023-04-01 23:59 UTC, Ch0ufleur commented on lib/widgets/views/login_view.dart
> +                                    Navigator.pushReplacementNamed(
pushNamed (tu veux pas remplacer sinon il peut pas go back)

2023-04-02 01:05 UTC, MrPuffs approved these changes

2023-04-02 01:05 UTC, MrPuffs commented on lib/widgets/views/forgot_password_view.dart
> +  late final TextEditingController _emailController = TextEditingController();
I don't think late is necessary

2023-04-02 03:09 UTC, Ch0ufleur approved these changes

2023-04-02 03:09 UTC, merged