86 video preview thomas
LOG8970-Team14/figure_skating_jumps pull request #69
Opened 2023-04-02 17:23 UTC by MrPuffs

2023-04-02 20:56 UTC, chrichriGeorgie requested changes

2023-04-02 20:56 UTC, chrichriGeorgie commented on lib/widgets/views/edit_analysis_view.dart
> +    setState(() {});
Mets les assignation dans le set state

2023-04-02 20:56 UTC, chrichriGeorgie commented on lib/widgets/views/edit_analysis_view.dart
> +  loadVideoData() async {
methode privée

2023-04-02 20:56 UTC, chrichriGeorgie commented on lib/widgets/views/edit_analysis_view.dart
> +  loadVideoData() async {
avec Future void comme retour

2023-04-02 22:08 UTC, MrPuffs commented on lib/widgets/views/edit_analysis_view.dart
> +    setState(() {});
je peux pas await dans un setState sadly

2023-04-02 22:53 UTC, MrPuffs commented on lib/widgets/views/edit_analysis_view.dart
> +    setState(() {});
nvm

2023-04-02 22:53 UTC, MrPuffs commented on lib/widgets/views/edit_analysis_view.dart
> +    setState(() {});
changed

2023-04-02 22:54 UTC, MrPuffs commented on lib/widgets/views/edit_analysis_view.dart
> +  loadVideoData() async {
changed

2023-04-03 00:09 UTC, chrichriGeorgie approved these changes

2023-04-03 01:04 UTC, Ch0ufleur approved these changes

2023-04-03 01:04 UTC, Ch0ufleur commented on lib/widgets/views/edit_analysis_view.dart
> +    _loadVideoData();
await?

2023-04-03 01:10 UTC, merged