Draft: Keep user signed in
LOG8970-Team14/figure_skating_jumps pull request #84
Opened 2023-04-08 03:46 UTC by cravethedave

2023-04-08 16:33 UTC, chrichriGeorgie requested changes

2023-04-08 16:33 UTC, chrichriGeorgie commented on lib/services/user_client.dart
> +        email: email, password: password, userInfo: userInfo);
Il faudrait également supprimer le user in DB on sign out et modifier le active session lors du change password (si c'est possible pour le change password, sinon supprimer le active session). Je mets le comment là puisque je ne peux pas commenter sur le sign out et le change password

2023-04-08 18:28 UTC, cravethedave commented on lib/services/user_client.dart
> +        email: email, password: password, userInfo: userInfo);
Good point, it will be done

2023-04-08 19:26 UTC, Ch0ufleur requested changes

2023-04-08 19:26 UTC, Ch0ufleur commented on lib/models/skating_user.dart
> +    SkatingUser skaterUser = SkatingUser(firstName, lastName, role, email, uID);
double check que le email casse pas tout autant sur firestore qu'ailleurs en te promenant dans l'app et vérifier que rien casse

2023-04-08 19:26 UTC, Ch0ufleur commented on lib/services/user_client.dart
> +      }
revoir ! vs ? et pt réarranger

2023-04-08 19:26 UTC, Ch0ufleur commented on lib/widgets/views/initial_redirect_route.dart
> +        UserClient().currentSkatingUser!.role == UserRole.coach
es tu sûr davoir besoin d'un else ? genre pushReplacement c'est pas comme un return ish?

2023-04-08 22:17 UTC, cravethedave commented on lib/models/skating_user.dart
> +    SkatingUser skaterUser = SkatingUser(firstName, lastName, role, email, uID);
I checked and all three uses have been reworked.

2023-04-08 22:59 UTC, Ch0ufleur approved these changes

2023-04-09 03:26 UTC, chrichriGeorgie approved these changes

2023-04-09 03:27 UTC, merged