refactor import
LOG8970-Team14/figure_skating_jumps pull request #96
Opened 2023-04-11 16:16 UTC by MrPuffs

2023-04-11 16:27 UTC, chrichriGeorgie requested changes
Juste t'assurer de merge main et de faire les modifications dans les imports si il y en a à faire en raison des changements de david

2023-04-11 16:27 UTC, chrichriGeorgie commented on lib/services/capture_client.dart
>  import 'external_storage_service.dart';
mettre package pour lui aussi (je pense qu'il n'y avait pas la ../ vu qu'ils sont dans le même folder)

2023-04-11 16:46 UTC, MrPuffs commented on lib/services/capture_client.dart
>  import 'external_storage_service.dart';
effectivement je l'ai changer

2023-04-11 16:46 UTC, MrPuffs commented on lib/widgets/layout/legend_move.dart
>  import 'color_circle.dart';
same

2023-04-11 20:54 UTC, chrichriGeorgie approved these changes

2023-04-13 13:35 UTC, cravethedave approved these changes

2023-04-13 13:37 UTC, chrichriGeorgie approved these changes

2023-04-13 13:37 UTC, merged