145 capture jumps refactor
LOG8970-Team14/figure_skating_jumps pull request #97
Opened 2023-04-12 19:14 UTC by cravethedave

2023-04-12 19:25 UTC, chrichriGeorgie requested changes
Blocked by https://github.com/LOG8970-Team14/figure_skating_jumps/pull/87

2023-04-12 23:57 UTC, chrichriGeorgie requested changes

2023-04-12 23:57 UTC, chrichriGeorgie commented on lib/utils/graphic_data_helper.dart
> +      jumps.addAll(test == null ? captureJumps : captureJumps.where(test));
Je mettrait un nom plus significatif à test

2023-04-12 23:57 UTC, chrichriGeorgie commented on lib/widgets/layout/athlete_view/progression_tab/progression_tab.dart
> +  final double _spacing = 100.0;
Ajuster avec les nouveaux ajustements de tablette

2023-04-13 01:17 UTC, cravethedave commented on lib/utils/graphic_data_helper.dart
> +      jumps.addAll(test == null ? captureJumps : captureJumps.where(test));
C'est literally un test boolean. Je sais pas quoi d'autre le nommer.
Also legacy code from someone else.

2023-04-13 01:20 UTC, chrichriGeorgie commented on lib/utils/graphic_data_helper.dart
> +      jumps.addAll(test == null ? captureJumps : captureJumps.where(test));
yeah fair, je sais pas tant comment le nommer non plus. Genre je pense à testCallback mais bof. I will resolve

2023-04-13 01:40 UTC, Ch0ufleur requested changes

2023-04-13 01:40 UTC, Ch0ufleur commented on lib/widgets/layout/athlete_view/progression_tab/progression_tab.dart
> +              padding: EdgeInsets.all(_spacing),
en fait c'est ici que tu dois l'ajuster :

EdgeInsets.all(ReactiveLayoutHelper.getHeightFromFactor(_spacing)

2023-04-13 12:55 UTC, Ch0ufleur approved these changes

2023-04-13 12:55 UTC, merged